apply plugin: 'maven-publish'

tasks.register('javadocJar', Jar) {
    def dokkaJavadoc = tasks.named('dokkaGeneratePublicationJavadoc')
    dependsOn dokkaJavadoc
    archiveClassifier.set('javadoc')
    from(dokkaJavadoc.flatMap { it.outputDirectory })
}

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.release
                groupId = providers.gradleProperty('drawingViewGroupId').get()
                artifactId = providers.gradleProperty('drawingViewArtifactId').get()
                version = providers.gradleProperty('drawingViewVersion').get()
                artifact javadocJar
            }
        }
    }
}
