import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.vojtkovszky.drawingview.example'

    defaultConfig {
        applicationId "com.vojtkovszky.drawingview.example"
        minSdk = providers.gradleProperty('minSdkVersion').get().toInteger()
        targetSdk = providers.gradleProperty('targetSdkVersion').get().toInteger()
        compileSdk = providers.gradleProperty('compileSdkVersion').get().toInteger()
        buildToolsVersion = providers.gradleProperty('buildToolsVersion').get()
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(providers.gradleProperty('javaVersion').get())
        targetCompatibility = JavaVersion.toVersion(providers.gradleProperty('javaVersion').get())
    }

    kotlin {
        compilerOptions {
            jvmTarget = JvmTarget.fromTarget(providers.gradleProperty('javaVersion').get())
        }
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    buildTypes {
        release {
            minifyEnabled = false
        }
    }

    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation project(":drawingview")

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}
